name: ettoolbox
channels:
  - conda-forge
dependencies:
  - python=3.11
  - astropy
  - beautifulsoup4
  - boto3
  - cmake
  - descartes
  - ephem
  - gdal>3.1
  - geopandas
  - hdfeos5
  - h5py
  - imageio
  - imageio-ffmpeg
  - jdcal
  - keras
  - matplotlib
  - netcdf4
  - nose
  - matplotlib
  - netcdf4
  - nose
  - pygeos
  - pygrib
  - pyhdf
  - pyresample
  - pysolar
  - pystac-client
  - python-dateutil
  - rasterio>1.0.0
  - requests
  - scikit-image
  - setuptools<58
  - shapely
  - tensorflow
  - termcolor
  - untangle
  - urllib3
  - xmltodict
  - xtensor
  - xtensor-python
  - wget
  - mgrs
  - pygrib
  - sentinelsat
  - typing-extensions
  - aiobotocore
  - boto3
  - aioitertools
  - botocore
  - earthaccess
  - multimethod
  - s3fs
  - tinynetrc
  - pip
  - pip:
     - rasters>=1.0.5
     - sun-angles
     - spacetrack
     - soil-capacity-wilting
     - solar-apparent-time
     - sentinel-tiles
     - pycksum
     - modisci
     - modland
     - koppengeiger
     - geos5fp
     - gedi-canopy-height
     - colored-logging
     - soil-capacity-wilting
     - modland
     - modisci
     - koppengeiger
     - geos5fp
     - bounded-pool-executor
     - harmonized-landsat-sentinel
     - python-cmr